### ISSUE TITLE
Your Polynomial Regressor uses the matrix class wrong.

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/machine-learning#1]
the matrix class isn't supposed to have the regressor operations in the matrix class it the regressor uses the matrix class to regress the polynomial, it's supposed to be the polynomial regressor using the matrix class to regress the polynomial. The specific line I'm talking about is line 23 in your polynomial_regressor.py

**Comment by RileyPaddock** [comment]
I fixed this and now It just uses the attributes of the Matrix class and not whole methods.
