### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#14]
I was looking through your commits and noticed that there were a bunch of binary files that were in the diffs. This doesn't actually affect anything you are doing, python generates these "cpython" binary files on its own for some caching thing, but it is annoying to sift through them when we review your code. The way to get rid of them is to add a new file `.gitignore` in the project directory with the following content:
```
**/__pycache__/
```
Then you have to manually remove all the pycache folders and commit to finish. This tells github that you don't want to add these python binary files in your commits, by saying "if I see a pycache folder in the directory name, then ignore it." (hence the git ignore.)

**Comment by RileyPaddock** [comment]
Thanks for this, these always bothered me to but I never knew how to get rid of them.
