### ISSUE TITLE
Make decision tree nodes recursive

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#15]
If you put the split function on your node class instead of the decision tree class, you'll save yourself a lot of writing due to recursion. I know currently it is recursive but on the decision tree, so moving it to the node should organize it a little better. Plus, if you run into problems in the future with infinite loops, it'll be easier to diagnose this way.

**Comment by RileyPaddock** [comment]
I made it so the split function is now a part of my node class and it recursivley calls split on it's low and high when it creates them.
