### ISSUE TITLE
Put the decision tree node in a different file

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#19]
Pretty much just the title.

 You should make a new file called `decision_tree_node.py` and move the `Node` class from `decision_tree.py` into there, then call it `DecisionTreeNode` or something. It will make your files very small and easy to work with.

I looked at your code for the decision tree and the node, and the code looks very clean! You did a good job organizing everything into where it should be. The one thing I would say (and this is nitpicking) is that some lines are a bit long, except that's what you get when you take advantage of list comprehensions unfortunately.

Great code!

**Comment by RileyPaddock** [comment]
I shortened the lines and separated the 2 classes into 2 files which is funny because I previously had them in separate files and someone left an issue saying I should merge them
