### ISSUE TITLE
Improve CSV reader for future assignments

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#22]
CSV is a really annoying thing to do, unless you realize that the makers of CSV didn't just make it to be horrible people. They made it so that anyone could store a table of data in a text file with ease, and so that you can also parse that text file with ease and get it back into table format. So, I think I found a more understandable and expandable way than you're currently doing it.

First of all, let's look at how you're executing it:

```
if read.split('\n').index(elem) != 0:
```
(line 136)

Here, you are getting the index of the current element. There are multiple things wrong with this method. 
1. What if there are duplicates? If there are duplicates, this function will just give you the first index of the value, not the actual value you're on. This will produce undefined behavior.
2. This requires a lot of extra computation. The index function has a big O of `O(n)`, meaning it will possibly traverse the entire list before executing the next code. When coding, you want to be aware of how fast your program will run, especially in a programming language not designed to be extremely fast like python.

```
first = [elem[0:quotes[0]-1],elem[quotes[0]:quotes[-1]],elem[quotes[-1]+1:len(elem)]]
```
(line 138)

The first thing with this line is that it's unreadable. Don't be afraid to add some spaces in there, they don't bite! Also, what does the variable `first` actually mean? Does it mean first quote? You should include this as a comment or the name of the variable.

### My way of doing this:

So far, we've encountered csv file that abide by the following rules:
1. Split by commas, unless they are inside quotes.
2. Each row in the table is separated by a newline (`\n`)

The second rule is easy to implement, you just do `string.split("\n")`. The first rule is the harder one. In your code, it looks like you desperately try to avoid looping through every single character to parse the string, instead you use all of python's built in string functions. My suggestion: just accept it. Try looping through every character, adding to a current string, until you reach a comma. If you aren't in a string, then add the current word to the row and reset it, otherwise add the comma to the string like anything else.

This method resembles something called a lexer, which is what programming languages use to parse code. When I made my csv parser using this method, my code became a lot cleaner and shorter, and I think the same will happen for you.

**Comment by RileyPaddock** [comment]
Thanks for the essay but we fixed this in an assignment anyways. Now we have the parse_line and stuff
