### ISSUE TITLE
Gotta pull stuff also review for your new DataFrame update in your repl.it 

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/machine-learning#5]
In your code, I see a lot of stuff that can be shortened, like in the order_by function, there is a lot of duplicated code, you can just have 2 if statements (non embedded) and have the order statement be just
```
if ascending:
    order = self.sorted_indicies(self.data_dict[column])[::-1]
else: 
    order = self.sorted_indicies(self.data_dict[column])
```
and generalize the alphabet and number indexing to shorten the code (I'm not gonna tell you how to cause its a trade secret)

**Comment by RileyPaddock** [comment]
I shortened it up so now it is only the one if else statement in order_by and I made the sorted_indicies function only 1 line too. I just did it late at night and forgot the sorted function existed.
