### ISSUE TITLE
Naive Bayes Classifier Tuple

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#7]
At the very end of your `naive_bayes_classifier.py` in your `classify` function, you return a string which is comprised of the name of the thing that you classified the observation as with an underscore and the python "atom" equivalent of the boolean value--you should instead use a tuple. I remember Justin changed the assignment in class, but I also remember that he didn't change the very last one (so you did follow the instructions), but you still should make this a tuple.

**Comment by RileyPaddock** [comment]
Fixed
