### ISSUE TITLE
Clean up probability and conditional probability in naive_bayes

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/machine-learning#8]
In your Naive Bayes classifier file, you have a couple of inefficiencies that you could clean up.

The first one is in the `probability` method, where you take the sum of 1 for all items that are equal to a certain value. Another way you could do this is just by getting the `count` of that value.

For example: if you have array `x = [0, 0, 1, 2, 3, 4, 4, 4, 5, 6]`, you could say `x.count(4)` and it would output `3`.

The next one is in the conditional probability function. A couple assignments ago, we made updates to our dataframes which allowed us to find rows where certain conditions were true. I used my `select_rows_where` function and the code is very legible and short; I think using it in your case as well would be very readable as well.

**Comment by RileyPaddock** [comment]
I fixed both of these. Thanks for the info on the count function I didn't realize that was a thing
