### ISSUE TITLE
Function Variable Naming

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/machine-learning#9]
In your `compute_average_distances` function in `k_nearest_neighbors_classifier.py`, you have a variable called `entry`, and I have no idea what `entry` is so if you either make it a dynamic variable like `var` in `for var in list_of_vars` or make the name more descriptive like from what I'm getting; for example `neighbor` or `neighbor_position`, also for the `averages` dictionary name, I would change it to be `average_distances`.

**Comment by RileyPaddock** [comment]
I actually refactored my whole k_nearest_neighbors class and this for loop now has a different name.
